version: '3.4'

services:
  hobbyhall.api:
    container_name: hobbyhall.api
    image: ${DOCKER_REGISTRY-}hobbyhall
    build:
      context: .
      dockerfile: HobbyHall.Api/Dockerfile
    ports:
        - "5000:5000"